### ISSUE TITLE
Angular 15 compatibility 

### ISSUE THREAD

**Issue by donbwhite** [Jordan-Hall/angular-material-rail-drawer-plugin#52]
I just upgraded my app to angular 15 and am getting an error with rails because when you currently upgrade with @15 or @latest it installs angular 15.0.1 but it appears that the plugin is set for 15.0.0. Could that be updated to be ^15.0.0 instead so any version of 15 would work?

**Comment by ChrTall** [comment]
Because this repository uses @nrwl/angular I can not upgrade the dependencies to Angular 15, because I am not familiar with it. Is the project still maintained? Maybe somebody could add instructions how to upgrade the dependencies to a new Angular version. Then other people can submit a PR. This lib currently blocks using Angular Material 15.

**Comment by Jordan-Hall** [comment]
Someone added the PR and I'll take a look tomorrow and push the changes. It's still maintained just not always as new version comes out straight away

**Comment by ChrTall** [comment]
Thank you for your effort.

**Comment by Jordan-Hall** [comment]
Thank you @ChrTall this has now been sorted. Please use version 2
